language: c
compiler:
- gcc

before-install:
- sudo apt-get update
install:
- sudo apt-get install build-essential libssl-dev flex bison gettext
script: "./configure && make && make install"

notifications:
  irc: "irc.chatfreedom.us#Ashtheme"
